version: '3'

services:

  express:
    build: ./
    ports:
      - 8081:8081

  influx:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    ports:
      - 8083:8083 # Admin interface
      - 8086:8086

  grafana:
    image: grafana/grafana
    ports:
      - 8082:3000